# These are supported funding model platforms

github: JIEMO
patreon: JIEMO
open_collective: JIEMO
ko_fi: JIEMO
tidelift: JIEMO
community_bridge: JIEMO
liberapay: JIEMO
issuehunt: JIEMO
otechie: JIEMO
custom: https://go.jie02.top/donate/ # Replace with a single custom sponsorship URL
