# These are supported funding model platforms

github: https://github.com/jiemo9527/jiemo9527.github.io
patreon: JIEMO
custom: https://go.jie02.top/donate/ # Replace with a single custom sponsorship URL
