repository: BYR-Navi/BYR-Navi
repository_url: https://github.com/BYR-Navi/BYR-Navi

timezone: Asia/Shanghai
lang: zh_CN

title: go.jie02.top
alias_en: GO导航
alias_cn: GO导航
description: A Navigation Website
keywords: 导航, 门户, go
url: https://go.jie02.top
established_at: "2016-10-01T00:00+08:00"

author: JIEMO
author_url: https://t.me./jiemo9527
organization: TEELAB
organization_url: https://teelab.net
contact: https://t.me./jiemo9527

image: /images/logo.png
logo: /images/logo.png
logo_dark: /images/logo-dark.svg
logo_white: /images/logo-white.svg

plugins:
- jekyll-seo-tag
- jekyll-sitemap

exclude:
- .gitignore
- .travis.yml
- LICENSE
- README.md
- CNAME
- Gemfile
- Gemfile.lock
- script
- vendor